[package]
name = "group"
version = "0.0.1"
authors = [ "manuel_puentes" ]
edition = "2018"

[lib]
name = "group"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
file_types = { version = "0.0.1", path = "../../commons/file_types" }
derive_more = "0"
serde = "1"

hc_utils = "0"
hdk3 = "0"
