[workspace]
members = [
    "zomes/group",
    # "zomes/request",
    # "zomes/username",
    "zomes/profiles",
    "zomes/contacts",
    "zomes/aggregator",
    "zomes/preference",
    "zomes/p2pmessage",
    "commons/file_types", 
    "zomes/webrtc"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
