[workspace]
members = [
    "zomes/preference",
    "zomes/p2pmessage",
    # "zomes/request",
    "zomes/username",
    "zomes/contacts"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
