[workspace]
members = [
    "zomes/preference",
    "zomes/p2pmessage",
    "zomes/contacts",
    "zomes/username",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
holo_hash = {git = "https://github.com/holochain/holochain", rev = "3675b58", package = "holo_hash"}

