[package]
name = "contacts"
version = "0.0.1"
authors = [ "tatssato" ]
edition = "2018"

[lib]
name = "contacts"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "=1.0.104"
hdk3 = {path = "../../../../../holochain/crates/hdk" }
derive_more = "0.99.9"