[package]
name = "contacts"
version = "0.0.1"
authors = [ "hcij" ]
edition = "2018"

[lib]
name = "contacts"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "=1.0.104"
hdk3 = { git = "https://github.com/holochain/holochain.git", branch = "develop" }
derive_more = "0.99.9"