[package]
name = "profiles"
version = "0.0.1"
authors = [ "hcij" ]
edition = "2018"

[lib]
name = "profiles"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
derive_more = "0"
serde = "1"
profiles = {git = "https://github.com/tatssato/profiles", branch="hc-0.0.114", package = "hc_zome_profiles"}
hdk = "0.0.114"
holo_hash = {version = "*", features = ["encoding"]}