[package]
name = "profiles"
version = "0.0.1"
authors = [ "hcij" ]
edition = "2018"

[lib]
name = "profiles"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
derive_more = "0"
serde = "1"
profiles = {git = "https://github.com/holochain-open-dev/profiles", rev="d18d99e126127fbd05730e4b3734a77f384d7556", package = "hc_zome_profiles"}
hdk = "0.0.115"
holo_hash = {version = "*", features = ["encoding"]}