name: CI
on:
  push:
    branches: [ develop ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - name: build-holochain
      run: |
        cd $GITHUB_WORKSPACE
        nix-shell . --run dnas/lobby &&  "CARGO_TARGET_DIR=target cargo build --release --target wasm32-unknown-unknown"
        nix-shell . --run dnas/lobby && "hc dna pack workdir/dna"
        nix-shell . --run dnas/lobby && "hc app pack workdir/happ"

    - name: test-holochain
      run: |
        cd $GITHUB_WORKSPACE
        nix-shell . --run dnas/lobby && npm install"
        nix-shell . --run dnas/lobby && npm run test" 